### PR TITLE
Generate SML diagrams using boost.Graph

### PR DESCRIPTION
**Pull request by JafarAbdi**

### CODE REVIEW

**Review by mamoll — COMMENTED** [review]
I like this a lot. In my version I had the class derive from the boost.graph graph type so that it was easy to pass the SmlTransitionGraph to other boost.graph algorithms (like boost::connected_components). Is there a reason to make it a member variable instead? I am not being pedantic, I am just trying to learn something. Adding a method to get a const& to graph_ is another way to do facilitate this.

**Comment by JafarAbdi** [comment]
Thanks! I update the class to derive from graph rather than having it as a member variable

**Comment by mamoll** [comment]
The latest commit adds Qt5 as a dependency, just to view a png image. That seems overkill to me. I'd modify the demo program to run `dot` (instead of the Qt5 viewer program), use PDF as the output format, and (optionally) call `xdg-open` to view the PDF.

**Review by mamoll — APPROVED** [review]
This looks good to me now. 

@tylerjw could you have a look at this, too?

**Comment by mamoll** [comment]
I merged this since we have some downstream code that needs this and none of the main SML code is affected by it.

**Pull request merged**
